#!/usr/bin/env node

const argv = require('yargs').argv
const { createFileLineReader } = require('./dist/FileLineReader')
const { checkerFor } = require('./dist/runner')
const { dictFile, first, last, pair, pairFile } = argv

const firstLastPair = first && last && [first, last]
const pairs = pair || firstLastPair || []

if (!dictFile) {
    throw Error('Missing dictFile argument --dict-file')
}

if (pairFile) {
    console.log('loading word pairs from word pair file', pairFile)    
    const onLine = (line) => {
        const words = line.split(' ')
        // console.log('read pair', words.join(','))
        pairs.push(words);
        // console.log(pairs)
    }
    createFileLineReader(pairFile, { onLine });
}

const callback = (pairsChecker) => {
    pairsChecker(pairs)
};

const checkWordPairs = checkerFor({dictFile, callback})
